### ISSUE TITLE
Speed up AppVeyor build

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/ror-dependencies#17]
At the moment our build on AppVeyor takes longer than the 60 minutes quota
Ideally, the build should take less than 55 minutes to complete

### TODO
- [x] Research ways to speed up the building proses
- [x] Disable unnecessary dependencies (?)

**Comment by only-a-ptr** [comment]
By hand I can say there's a number of OGRE targets we can omit:
* ParticleFX component
* Property component
* BSPSceneManager
* PCZSceneManager
* OgreVolume
* OctreeZone - not related to 'OctreeSceneManager' that we use.
* OgreRTShaderSystem - Research needed, we touch it in the codebase somehow but I don't think it ever did anything useful.

**Comment by Speciesx** [comment]
ParticleFX: Is used for particles
Property: only available when ogre build up with boost.

**Comment by Speciesx** [comment]
also unused by ror.
ogredeps: 
OGREDEPS_BUILD_AMD_QBS
OGREDEPS_BUILD_NVIDIA_NVAPI
