### ISSUE TITLE
Build failed: Win10, VS2015sp2

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/ror-dependencies#2]
Hello.

Yesterday night I tried building deps on my laptop and it somehow failed while building OGRE. I can't look more closely now.

Attached are 2 build logs: the initial build and a second build (to see the failures more easily): 

build1: https://www.dropbox.com/s/0cso9kkq1p3tis8/buid01-12succeeded-4failed.log?dl=0
build2: https://www.dropbox.com/s/pbzeto9mpjp14p2/build02-sameResult.log?dl=0
CMakeCache: https://www.dropbox.com/s/tz0agxlqzoxso55/CMakeCache.txt?dl=0

My spec: Windows10pro, CPU i7-2637M, 4GB RAM, CMake 3.5.2 (ZIP)

PS: Hmmm.... my CMake is not in PATH, could that be a problem?

**Comment by mikadou** [comment]
Sorry, I wasn't subscribed to notifications from this repo. Just discovered this issue now.

Are you building in `Release` mode?

**Comment by only-a-ptr** [comment]
> Are you building in Release mode?
Nope, `Debug`.

**Comment by mikadou** [comment]
Could you try a clean build in Release mode? I only focused on building in Release mode so far. Of course being able to produce dependencies with Debug information would be nice, but isn't a priority for me. My motivation for this stems from the CMake build system cleanup in https://github.com/RigsOfRods/rigs-of-rods/pull/924 . I knew these changes would only be acceptable if it doesn't break building on Windows. However the existing dependencies Zip-package (and those created by @Speciesx) are not compatible with this approach because the directory structure differs from what most CMake Find-modules expect. Hence I created this ror-dependencies CMake script, to allow to straightforwardly compile the dependecies by oneself.

Actually my hope was that @Speciesx and others would pickup on this, iron out further bugs and eventually figure out how to do Debug mode builds.

**Comment by Speciesx** [comment]
```
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_GL.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_GL.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_GL.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_Direct3D9.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_Direct3D9.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/RenderSystem_Direct3D9.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/OgreMain.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/OgreMain.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error		File D:/ror/dev/ror-dependencies/build_x86/Dependencies_Windows_Visual-Studio-14-2015/bin/release/OgreMain.dll does not exist.	mygui	D:\ror\dev\ror-dependencies\build_x86\CUSTOMBUILD	1	
Error	LNK1104	cannot open file 'OgreMain.lib' [D:\ror\dev\ror-dependencies\build_x86\Build\caelum\main\Caelum.vcxproj]	caelum	D:\ror\dev\ror-dependencies\build_x86\LINK	1	
Error	LNK1104	cannot open file 'OgreMain.lib' [D:\ror\dev\ror-dependencies\build_x86\Build\caelum\main\Caelum.vcxproj]	caelum	D:\ror\dev\ror-dependencies\build_x86\LINK	1	
```
This is the only error i get, when i try to building in debug mode. 
MyGUI and Caelum debug build fails, because it tries to find the ogre release build, instead of debug build.

**Comment by only-a-ptr** [comment]
@mikadou Tonight I built the latest deps on my desktop machine. Went smoothly for Release, RelWithDebugInfo built, Debug failed with OgreMain for some reason.

https://www.dropbox.com/sh/phwhoxv3a20yvk5/AAAn7cHjlKbNDRyg1Dk0Ub-6a?dl=0

Also, minor glitch, one of the resulting include paths is:
```
D:\Projects\Git\rigs-of-rods\source\main\The ogre include path to use
```
