### ISSUE TITLE
Replace OGRE bitbucket link with GitHub

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/ror-dependencies#8]
So we don't have to install hg just to clone one project

https://github.com/OGRECave/ogre

**Comment by only-a-ptr** [comment]
Hmm... makes sense, except the OGRE github repo is unofficial, it's a rogue initiative of one team member. I need to take a closer look at it. Basically it doesn't make much difference for v1-9 which is a stable release, but we'd probably want to revert it for v2-1+ which receive development at Bitbucket.
